<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.*" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.*" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.*" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlow.Contracts\TaskFlow.Contracts.csproj" />
    <ProjectReference Include="..\TaskFlow.Application\TaskFlow.Application.csproj" />
    <ProjectReference Include="..\TaskFlow.Infrastructure\TaskFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
