<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="11.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlow.Contracts\TaskFlow.Contracts.csproj" />
  </ItemGroup>

</Project>
